### ISSUE TITLE
CSS & JS wird immer geladen

### ISSUE THREAD

**Issue by vm1601com** [1601com/social-media-bar#9]
## Ziel ([SMART](https://de.wikipedia.org/wiki/SMART_(Projektmanagement)))
*CSS und JS Dateien der Erweiterung werden nach einer Installation auch wenn kein Modul im Layout verbaut ist geladen. Die Dateien sollen optional geladen werden können und nur erscheinen wenn ein Modul eingebunden ist.*

## ToDos // @vm1601com  // Aufwand ~2h
* [x] Fehleranalyse woran es liegt
* [x] Optionale Checkbox zum Laden der internen Styles
  * [x] Theme Auswahl soll erst nach anwählen der Checkbox erscheinen
* [x] Optionale Checkbox zum Laden des share PopUp Scripts
* [x] CSS & JS erst in Module compile laden lassen

## Ressourcen & Projektinformationen
* **Projektleitung:** @LBeckX 
* **Q-Aufgabe:** 
* **Stundenfreigabe:** x h
* **Deadline:** TT.MM.JJJJ

## Status
* [x] Briefing / KickOff
* [x] Aufwandseinschätzung abgegeben
* [x] Freigabe erhalten
* [x] Umsetzung begonnen *(MA)*
* [x] Umsetzung abgeschlossen *(MA)*
* [x] Neuer Release angelegt und auf Packagist aktualisiert
* [x] [Qualitätssicherung](https://github.com/1601com/Agenturprozess/wiki/Prozesse:-DigitalMedia:-2AC-4AC) *(PL + MA)*

**Comment by vm1601com** [comment]
@LBeckX kannst du mir das so freigeben und worauf soll ich das dann buchen?

**Comment by LBeckX** [comment]
@vm1601com habe DIr eine Aufgabe angelegt in Betreuung 2021.

**Comment by vm1601com** [comment]
Fehler behoben und Optimierungen durchgeführt: 576780f428812313bfd5a2278d5d5171e8450529

Habe die CSS und JS Datei jetzt aus der contao/config Datei herausgeschmissen und lasse diese jetzt nur laden wenn sie auch benötigt werden. Hierfür habe ich in den smBar Einstellungen zwei neue Checkboxen angelegt durch welche die Dateien aktiviert werden können. 

Habe außerdem noch ein paar Bug fixes und etwas an der Nutzerfreundlichkeit der Erweiterung im Backend gemacht.

##

@LBeckX magst du hier noch eine QS machen? Bin hier durch und es kann mMn zu.

**Comment by LBeckX** [comment]
@vm1601com aktualisieren auf dem Agentur-CMS

**Comment by vm1601com** [comment]
@LBeckX habe die Erweiterung im Agentur-cms aktualisiert und es sieht alles gut aus.

Ich melde mich dann noch für die finale QS, danach kann hier zu.

**Comment by LBeckX** [comment]
Ist gecheckt, Line-Height wird noch angepasst und dann ist das durch. Ticket kann schon zu

**Comment by vm1601com** [comment]
CSS Anpassungen erledigt 979c489c83bf7021a544cdfef8b035b2d6819e71

Habe noch einen neunen Release angelegt und die Erweiterung auf Packagist aktualisiert.

Da Packagist immer etwas braucht, werde ich es später noch im Agentur-cms aktualisiere.
